version: '3'
services:
  main:
    image: toreskog/cloudmaker:latest
    build: 
      context: .
      args:
        CF_Key: $CF_Key
        CF_Email: $CF_Email
    environment:
      CF_Key: $CF_Key
      CF_Email: $CF_Email
    ports:
      - '80:80'
      - '443:443'